In [1]:
%matplotlib inline
import os
os.environ['THEANO_FLAGS'] = "mode=FAST_RUN,device=cpu,floatX=float32"
import theano
import theano.tensor as T
import config
import numpy as np
import matplotlib.pyplot as plt

/Library/Python/2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [2]:
import network
import network.normFlow as nf
import utils
import utils.mathT as mathT
import utils.theanoGeneral as utilsT
import utils.optimizers as optimizers
import utils.plotZ as plotZ
import models.mars as model

In [5]:
# learning how to use theano.tensor.switch

a = T.fmatrices('a')
z = T.switch( a>3, a, 5  )
fz = theano.function([a],outputs=z)

In [6]:
print fz( np.asarray([[2,3,4],[5,6,7]],dtype='float32'))

[[ 5.  5.  4.]
 [ 5.  6.  7.]]


In [3]:
DIM = 2
SAMPLINGNUM = 30
floatX = utils.floatX

x = utilsT.sharedf(2)
z = T.fmatrix()

# constructing graphical model
mb = model.Banana()
mb.setX(3)
# setting cost variable
logpxz = mb.logPxz(z)
logpz  = mb.logPrior(z)

In [6]:
f1 = theano.function([],outputs=logpxz)
f2 = theano.function([],outputs=logpz)

MissingInputError: ("An input of the graph, used to compute Prod{axis=[1], acc_dtype=float64}(<TensorType(float32, matrix)>), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", <TensorType(float32, matrix)>)

In [5]:
zsamples = np.asarray([[0,0],[1,2]],dtype=floatX)
xsamples = np.asarray([[0]],dtype=floatX)
print f1(xsamples,zsamples)
print f2(zsamples)

NameError: name 'f1' is not defined

In [5]:
a = utilsT.sharedf( 50 )
b = utilsT.sharedf( np.asarray([1,2,3]) )

In [8]:
c = b + 5
fb = theano.function([], outputs=c)

In [9]:
fb()

array([ 6.,  7.,  8.], dtype=float32)