In [1]:
%matplotlib inline
import os
os.environ['THEANO_FLAGS'] = "mode=FAST_RUN,device=cpu,floatX=float32"
import theano
import theano.tensor as T
import config
import numpy as np
import matplotlib.pyplot as plt

/Library/Python/2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [5]:
import network
import network.normFlow as nf
import utils
import utils.mathT as mathT
import utils.theanoGeneral as utilsT
import utils.optimizers as optimizers
import utils.plotZ as plotZ
import models.mars as model
floatX = utils.floatX

In [41]:
# learning 3-dim tensors
w = T.fmatrix()
x = T.tensor3()
y = T.dot( x, w )
fy = theano.function([x,w],outputs=y)

# mask = np.asarray([np.eye(2) for i in range(3)],dtype=floatX)
i = theano.shared(np.arange(2))
xdiag = x[:,i,i]
fxdiag = theano.function( [x], outputs=xdiag  )

In [42]:
xn = np.asarray( [ [[0,0],[0,0]], [[1,1],[0,1]], [[1,2],[0,3]] ], dtype=floatX   )
wn  = np.asarray( [ [0,0],[1,1] ], dtype=floatX ) 

In [91]:
x = theano.shared(np.asarray(np.eye(3),dtype=floatX))
print x[1].eval()

[ 0.  1.  0.]


In [95]:
ys = list()
for i in range(2):
    y = theano.shared( np.asarray(np.arange(6)+i,dtype=floatX) )
    ys.append(y)
yy = T.concatenate(ys).reshape((2,3,2))
print yy.eval()

[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]]


In [88]:
x1n = np.ones((2,3,4))
for i in range(2):
    for j in range(3):
        x1n[i,j,:] = np.arange(4)
x1 = theano.shared(x1n)
x2 = x1.dimshuffle(0,1,'x',2) + theano.shared(np.zeros((2,3,4,4)))
print x2.eval()

[[[[ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]]

  [[ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]]

  [[ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]]]


 [[[ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]]

  [[ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]]

  [[ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]
   [ 0.  1.  2.  3.]]]]


In [102]:
x1 = theano.shared(np.arange(12)).reshape((3,2,2))
y1 = theano.shared(np.ones(3))
y1_new = y1.dimshuffle(0,'x','x')
z1 = x1 - y1_new
print z1.eval()
print x1.eval()

[[[ -1.   0.]
  [  1.   2.]]

 [[  3.   4.]
  [  5.   6.]]

 [[  7.   8.]
  [  9.  10.]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
